### ISSUE TITLE
Package has no version tags

### ISSUE THREAD

**Issue by theRatramnus** [demharusnam/SwiftUIDrag#1]
The package doesn’t have version tags and thus can’t be used with Swift Playgrounds on iPad. I would like for it to have those so i can use it…

**Comment by demharusnam** [comment]
Apologies for the delay in my response - I'm no longer actively maintaining this project. However, this package has various version [tags](https://github.com/demharusnam/SwiftUIDrag/tags) associated with it. Though, I've added an official [release tag](https://github.com/demharusnam/SwiftUIDrag/releases/tag/0.0.11) if that helps.

Furthermore, if you're unable to find this package by searching for its name, try searching for the [url](https://github.com/demharusnam/SwiftUIDrag).

Hope this helps! 😄

**Comment by theRatramnus** [comment]
Apologies for my absolutely inappropriate tone, I should have been a lot nicer, but this was my first issue and so I didn’t know - and thank you so much for the solution: it works now!
